apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bottlerocket-demo
  region: us-west-2
  version: "1.21"

managedNodeGroups:
  - name: bottlerocket-demo-ng
    instanceType: t3.medium
    minSize: 1
    maxSize: 4
    desiredCapacity: 3
