apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bottlerocket-demo2
  region: us-west-1
  version: '1.21'

managedNodeGroups:
  - name: bottlerocket-demo-ng
    instanceType: m5.large
    amiFamily: Bottlerocket
    minSize: 1
    maxSize: 4
    desiredCapacity: 3
